name: Deploy to Web Server

on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ttyllc/python-app.git
          ref: master
      - name: Disable strict host key checking
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - name: Copy code to server
        run: sshpass -p ${{ secrets.SSH_PRIVATE_KEY }} scp -r . cdci_sample_user@ims2.ttyllc.net:/home/cdci_sample_user/python_app
      - name: Restart web server
        run: sudo systemctl restart apache2
      - name: List directory contents
        run: ls /home/cdci_sample_user/python_app
        shell: bash



  
